# Generated by Django 4.2.2 on 2023-06-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='entyr_id',
            new_name='market_id',
        ),
    ]
