# Generated by Django 4.2.2 on 2023-06-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_entyr_id_market_market_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='department',
            field=models.CharField(default='Tech', max_length=50),
            preserve_default=False,
        ),
    ]
